### ISSUE TITLE
 Illegal offset type in isset or empty when sending out a notification

### ISSUE THREAD

**Issue by dgagnon** [AbuseIO/AbuseIO#127] opened 2016-08-17 15:39 UTC
This is with default notification configuration.

`Exception trace:
 () at /opt/abuseio/bootstrap/cache/compiled.php:14081
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /opt/abuseio/bootstrap/cache/compiled.php:14081
 Illuminate\View\Factory->make() at /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:748
 view() at /opt/abuseio/vendor/abuseio/notification-mail/src/Mail.php:130
 AbuseIO\Notification\Mail->send() at /opt/abuseio/app/Jobs/Notification.php:44
 AbuseIO\Jobs\Notification->send() at /opt/abuseio/app/Jobs/Notification.php:111
 AbuseIO\Jobs\Notification->walkList() at /opt/abuseio/app/Console/Commands/Housekeeper/NotificationsCommand.php:141
 AbuseIO\Console\Commands\Housekeeper\NotificationsCommand->handle() at n/a:n/a
 call_user_func_array() at /opt/abuseio/bootstrap/cache/compiled.php:1187
 Illuminate\Container\Container->call() at /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php:150
 Illuminate\Console\Command->execute() at /opt/abuseio/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
 Illuminate\Console\Command->run() at /opt/abuseio/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at /opt/abuseio/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /opt/abuseio/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:107
 Illuminate\Foundation\Console\Kernel->handle() at /opt/abuseio/artisan:36
`

Note that the line number for Mail.php is not the right one since I added some debug code to try and figure this out.   The problematic line is:

`$htmlmail = view(['template' => $htmlmail], $replacements)->render();`

**Comment by dgagnon** [comment] 2016-08-17 15:53
This is with a composer install, v4.0.1

**Comment by dgagnon** [comment] 2016-08-17 16:04
Try latest dev composer install, full stack trace here:  http://pastebin.com/UX3fFpBt

**Comment by dgagnon** [comment] 2016-08-17 16:47
Some information gathered from #laravel on freenode:

> view() goes to ViewFactory->make (https://github.com/laravel/framework/blob/5.2/src/Illuminate/View/Factory.php#L157) which does: "isset($this->aliases[$view])", so your doing "isset($this->aliases[["template" => "xxx"]])", hence illegal offset type as an array cannot be a key

**Comment by dgagnon** [comment] 2016-08-17 16:51
I believe the problematic commit is:

https://github.com/AbuseIO/notification-mail/commit/30147ee063493348cf4b2adfe19ce28c1ab66734

**Comment by joverthegrey** [comment] 2016-08-17 16:54
Thanks, in notification-mail version 1.2.2 and higher we use another version of blade template views.  The problem is that i didn't pin the max version in the composer.json.

Quick fix: replace "abuseio/notification-mail": "1.2.*", with "abuseio/notification-mail": "1.2.1", in composer.json

I'll commit it later tonight

**Comment by joverthegrey** [comment] 2016-08-17 16:54
and run composer update :)

**Comment by joverthegrey** [comment] 2016-08-17 16:56
1.2.2 and higher are used by the dev branch (4.1)

**Comment by dgagnon** [comment] 2016-08-17 16:58
Thanks!

**Comment by joverthegrey** [comment] 2016-08-17 17:49
Fixed in PR #128

**Closed** 2016-08-17 17:50 UTC
