### ISSUE TITLE
Project Honeypot parser does not match reports

### ISSUE THREAD

**Issue by jviersel** [AbuseIO/AbuseIO#43] opened 2015-10-05 19:02 UTC
I don't know if i misconfigured something at project honeypot or if they changed their format. The mails i receive look like this:

```
Below is your Project Honey Pot Monitor Report for 09/02/2015 - 10/03/2015. To view your report in more detail, including more information on any of the listed IPs, please visit your online report at:

http://www.projecthoneypot.org/monitor_report.php

The report summarizes the IPs you currently are monitoring. If you have changed your Monitor Settings during the report period then the report will reflect the settings at the end of the period.
Need to monitor more IPs? You can now sign up for the Advanced Monitor Service. For more details, click here:

https://www.projecthoneypot.org/monitor_upgrade_1.php

This email was generated and sent to your account by a Project Honey Pot account held by somebody@example.com.

---------------------------------------


Report Date Range: 09/02/2015 - 10/03/2015
IPs Monitored: 4,608
Malicious IPs : 5
- Harvesting IPs: 3
- Email Spamming IPs: 0
- Dictionary Attacks IPs: 0
- Comment Spamming IPs: 2
Other Potentially Suspicious IPs : 0

IPs Engaged In Harvesting On Your Network:

1.2.3.4


IPs Engaged In Email Spamming On Your Network:

none


IPs Engaged In Dictionary Attacks On Your Network:

none


IPs Engaged In Comment Spamming On Your Network:

1.2.3.4


Other Potentially Suspicious IPs On Your Network:

none

---------------------------------------

Please see your Monitor Report for more details on the activity of the reported IPs. You have elected to receive this message Weekly. To change the frequency with which you receive this message, or stop receiving it entirely, please visit:

http://www.projecthoneypot.org/monitor_settings.php

If you would rather not receive this report unless there is activity on your network, please visit:

http://www.projecthoneypot.org/monitor_settings.php
```

**Comment by djkrul** [comment] 2015-10-06 06:01
The parser looks for the abuse class, which should be included right after the listed IP addresses, i.e. "1.2.3.4 (S)". 

My last report from 22-09 does include this, so I wonder if this is a bug or indeed a change of the report format. Do you have any other reports prior to this date?

What are your settings on http://www.projecthoneypot.org/monitor_settings.php ? I've got 'send notification daily with **detailed/expanded** network abuse information'. Do you have that too or is yours set to **brief / summarized**?

**Comment by kruisdraad** [comment] 2015-10-06 09:03
The problem seems to be in two different reporting formats. Paid and Free subscriptions have each their own format. I've contacted projecthoneypot to get some clarification on these formats and if they wouldnt create something parseable.

**Comment by jviersel** [comment] 2015-10-06 11:25
I've re-written the Project Honeypot parser for the other format. Maybe we can merge the code of the parsers so it can parse both formats?

**Comment by kruisdraad** [comment] 2015-10-06 14:26
I already make the code and validated it. But i need to make sure this is the only two formats or that we need to consider other formats too to prevent similar problems in the feature.

Code for the 4.x branch (not committed yet) would be:

<?php

namespace AbuseIO\Parsers;

class Projecthoneypot extends Parser
{
    /**
     * Create a new Projecthoneypot instance
     */
    public function __construct($parsedMail, $arfMail)
    {
        parent::__construct($parsedMail, $arfMail, $this);
    }

    /**
     * Parse attachments
     * @return Array    Returns array with failed or success data
     *                  (See parser-common/src/Parser.php) for more info.
     */
    public function parse()
    {
        $reports = [];

        $body = $this->parsedMail->getMessageBody();
        $body = str_replace('\r', '', $body);
        $body = str_replace(
            'Other Potentially Suspicious IPs On Your Network:',
            'IPs Engaged In Potentially Suspicious On Your Network:',
            $body
        );

        if (preg_match_all(
            '/Engaged\sIn\s(.+?)\s.+?Network:[\n]+(.+?)^\n/ms',
            $body,
            $matches
        )) {
            if (!empty($matches[1]) &&
                !empty($matches[2]) &&
                is_array($matches[1]) &&
                is_array($matches[2]) &&
                count($matches[1]) == 5 &&
                count($matches[2]) == 5
            ) {
                foreach ($matches[2] as $key => $ipSet) {
                    foreach (array_filter(explode("\n", $ipSet)) as $ip) {
                        $reports[] = $report = [
                            'feed' => $matches[1][$key],
                            'ip' => $ip,
                        ];
                    }
                }
            }

            foreach ($reports as $report) {
                if ($report['ip'] != 'none') {
                    $this->feedName = $report['feed'];

                    // If feed is known and enabled, validate data and save report
                    if ($this->isKnownFeed() && $this->isEnabledFeed()) {
                        // Sanity check
                        if ($this->hasRequiredFields($report) === true) {
                            // Event has all requirements met, filter and add!
                            $report = $this->applyFilters($report);

                            $this->events[] = [
                                'source' => config("{$this->configBase}.parser.name"),
                                'ip' => $report['ip'],
                                'domain' => false,
                                'uri' => false,
                                'class' => config("{$this->configBase}.feeds.{$this->feedName}.class"),
                                'type' => config("{$this->configBase}.feeds.{$this->feedName}.type"),
                                'timestamp' => time(),
                                'information' => json_encode($report),
                            ];
                        }
                    }
                }
            }
        } else {
            $this->warningCount++;
        }

        return $this->success();
    }
}

**Comment by kruisdraad** [comment] 2015-10-07 20:10
Updated and confirmed working for version 4.0.

This could be used to backport this into 3.0

**Closed by kruisdraad** 2015-10-07 20:10 UTC
